In [ ]:
import numpy as np

In [ ]:
arr = np.array([2, 4, 6, 7, 8])
arr[1]

4

In [ ]:
arr[0]

2

In [ ]:
cartela_bingo = np.array([[16, 10,  3, 15],
                            [14, 23, 17, 27],
                            [ 6, 19,  3,  1],
                            [10,  4, 18, 19]])
cartela_bingo

array([[16, 10,  3, 15],
       [14, 23, 17, 27],
       [ 6, 19,  3,  1],
       [10,  4, 18, 19]])

In [ ]:
cartela_bingo[:, 1].reshape((4,1))

array([[10],
       [23],
       [19],
       [ 4]])

In [ ]:
cartela_bingo[0]

array([16, 10,  3, 15])

In [ ]:
np.sort(cartela_bingo)

array([[ 3, 10, 15, 16],
       [14, 17, 23, 27],
       [ 1,  3,  6, 19],
       [ 4, 10, 18, 19]])

In [ ]:
np.sort(cartela_bingo, axis=0)

array([[ 6,  4,  3,  1],
       [10, 10,  3, 15],
       [14, 19, 17, 19],
       [16, 23, 18, 27]])

## 1.1 Explorando Ecossistemas:
Como bióloga marinha, me encontrei em uma expedição nas profundezas do Oceano Pacífico, onde estávamos estudando a biodiversidade e a saúde dos recifes de coral. O catálogo abaixo demonstra dados das espécies encontradas, considere a seguinte ordem de colunas:

**ID da espécie, quantidade de representantes encontrados, profundeza, tamanho médio da espécie**



*  Selecione a segunda coluna com a quantidade de espécies encontradas e adicione em um array as qtd_especies.
*  De qtd_especies selecione apenas as primeiras 3 quantidades e print
*  Print as 5 últimas quantidades de espécies
*  Crie um array que contenha apenas os tamanhos das espécies e ordene por ordem crescente






In [3]:
import numpy as np

In [4]:
especies = np.array([[747,  89,  33,   5],
                    [623, 123,  32,  13],
                    [501,  22,  49,   2],
                    [116, 101,  42,  10],
                    [297,  56,  69,  22],
                    [613,  64,  27,   7],
                    [295,  84,  29,  14],
                    [692, 105,  72,  16],
                    [229, 103,  35,   5],
                    [374, 124,  70,   1]])
especies

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1]])

In [5]:
especies = np.array([[747, 89, 33, 5], [623, 123, 32, 13], [501, 22, 49, 2],
                     [116, 101, 42, 10], [297, 56, 69, 22], [613, 64, 27, 7],
                     [295, 84, 29, 14], [692, 105, 72, 16], [229, 103, 35, 5],
                     [374, 124, 70, 1]])

qtd_especies = especies[:, 1]  
print("Quantidade de espécies encontradas:\n", qtd_especies)


Quantidade de espécies encontradas:
 [ 89 123  22 101  56  64  84 105 103 124]


In [6]:
primeiras_3_qtd = qtd_especies[:3]
print("Primeiras 3 quantidades de espécies encontradas:\n", primeiras_3_qtd)

Primeiras 3 quantidades de espécies encontradas:
 [ 89 123  22]


In [7]:
ultimas_5_qtd = qtd_especies[-5:]
print("Últimas 5 quantidades de espécies encontradas:\n", ultimas_5_qtd)


Últimas 5 quantidades de espécies encontradas:
 [ 64  84 105 103 124]


In [8]:
tamanhos = especies[:, 3]
tamanhos_ordenados = np.sort(tamanhos)
print("Tamanhos das espécies ordenados:\n", tamanhos_ordenados)


Tamanhos das espécies ordenados:
 [ 1  2  5  5  7 10 13 14 16 22]


## Filtrando Arrays

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
mask = arr1 % 3 == 0
mask

array([False, False,  True, False, False])

In [ ]:
pessoas_id_idade = np.array([[1, 22], [2, 21], [3, 27], [4, 26]])
pessoas_id_idade

array([[ 1, 22],
       [ 2, 21],
       [ 3, 27],
       [ 4, 26]])

In [ ]:
cartela_bingo = np.array([[16, 10,  3, 15],
       [14, 23, 17, 27],
       [ 6, 19,  3,  1],
       [10,  4, 18, 19]])
cartela_bingo

array([[16, 10,  3, 15],
       [14, 23, 17, 27],
       [ 6, 19,  3,  1],
       [10,  4, 18, 19]])

## 1.2 Ainda usando o Array de espécies marítimas.

*   Usando um index booleano crie um array que contém os dados da maior espécie encontrada (considerando o seu tamanho), esse valor corresponde ao valor 22.

*   Usando fency index faça um array que contém apenas dados da espécie com ID 297
*   Usando np.where() faça um array com a linha com dados correspondentes a espécie com 105 representantes encontrados.
*   Considere a profundeza em que o espécie foi encontrada substitua valores maiores que 60 com "Profundo"



In [ ]:
especies

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1]])

In [9]:
maior_tamanho_index = especies[:, 3] == 22
maior_especie = especies[maior_tamanho_index]
print("Dados da maior espécie encontrada:\n", maior_especie)


Dados da maior espécie encontrada:
 [[297  56  69  22]]


In [10]:
id_297 = especies[especies[:, 0] == 297]
print("Dados da espécie com ID 297:\n", id_297)


Dados da espécie com ID 297:
 [[297  56  69  22]]


In [11]:
representantes_105 = np.where(especies[:, 1] == 105)
dados_representantes_105 = especies[representantes_105]
print("Dados da espécie com 105 representantes encontrados:\n", dados_representantes_105)


Dados da espécie com 105 representantes encontrados:
 [[692 105  72  16]]


In [12]:
profundeza = especies[:, 2]
profundeza_substituida = np.where(profundeza > 60, "Profundo", profundeza)
print("Profundidade com valores substituídos:\n", profundeza_substituida)


Profundidade com valores substituídos:
 ['33' '32' '49' '42' 'Profundo' '27' '29' 'Profundo' '35' 'Profundo']


## 1.3 Ainda no conjunto 'especies'.

*   Adicione mais 2 espécies ao array: [[204, 10, 40, 12], [392, 11, 81, 11]]
*   Adicione mais uma coluna na no array original agora com o número de espécies encontradas com que indica se o animal enxerga ou não: [0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0]


In [13]:
novas_especies = np.array([[204, 10, 40, 12], [392, 11, 81, 11]])
especies_atualizadas = np.vstack([especies, novas_especies])
print("Array de espécies atualizado:\n", especies_atualizadas)


Array de espécies atualizado:
 [[747  89  33   5]
 [623 123  32  13]
 [501  22  49   2]
 [116 101  42  10]
 [297  56  69  22]
 [613  64  27   7]
 [295  84  29  14]
 [692 105  72  16]
 [229 103  35   5]
 [374 124  70   1]
 [204  10  40  12]
 [392  11  81  11]]


In [15]:
num_linhas = especies_atualizadas.shape[0]
print("Número de linhas em especies_atualizadas:", num_linhas)


Número de linhas em especies_atualizadas: 12


In [18]:
especies = np.array([
    [747, 89, 33, 5],
    [623, 123, 32, 13],
    [501, 22, 49, 2],
    [116, 101, 42, 10],
    [297, 56, 69, 22],
    [613, 64, 27, 7],
    [295, 84, 29, 14],
    [692, 105, 72, 16],
    [229, 103, 35, 5],
    [374, 124, 70, 1]
])

novas_especies = np.array([[204, 10, 40, 12], [392, 11, 81, 11]])
especies_atualizadas = np.vstack([especies, novas_especies])

num_linhas = especies_atualizadas.shape[0]
print("Número de linhas em especies_atualizadas:", num_linhas)

nova_coluna = np.array([0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1])  

nova_coluna = nova_coluna.reshape(-1, 1)  
especies_com_coluna = np.hstack([especies_atualizadas, nova_coluna])
print("Array de espécies com nova coluna:\n", especies_com_coluna)


Número de linhas em especies_atualizadas: 12
Array de espécies com nova coluna:
 [[747  89  33   5   0]
 [623 123  32  13   1]
 [501  22  49   2   0]
 [116 101  42  10   0]
 [297  56  69  22   0]
 [613  64  27   7   0]
 [295  84  29  14   1]
 [692 105  72  16   0]
 [229 103  35   5   1]
 [374 124  70   1   1]
 [204  10  40  12   0]
 [392  11  81  11   1]]


## 1.4 Cálculo com Array

*   O cliente que teve acidente abaixo da média nos últimos 2 anos,
ganhará um desconto no seu seguro. Identifique-os.
* Qual cliente teve pelo menos 2 anos sem cometer acidentes?
* Uma professora quer que seus alunos apliquem a função (3x + 2y +
x*y) em um conjunto de dados. Ela dá dois arrays aos estudantes e
pede que seja feita essa operação.
* A mesma professora percebeu que houve um erro em todas as provas
dos estudantes e esqueceu de anotar a nota de trabalhos
apresentados durante o semestre. Já que foi feito em grupo ela vai
adicionar a mesma nota para todos os estudantes. No array cada
estudante representa uma linha e cada coluna uma prova. Adicione
para cada prova de cada estudante os valores: 1, 2, 1.

In [25]:
acidentes = np.array([[1, 3, 2],
                      [0, 1, 0],
                      [2, 1, 4],
                      [0, 0, 0],
                      [1, 1, 0]])

media_acidentes = acidentes.mean(axis=1)

media_geral = media_acidentes.mean()

clientes_abaixo_media = np.where(media_acidentes < media_geral)[0]

print("Clientes com acidentes abaixo da média:", clientes_abaixo_media)

Clientes com acidentes abaixo da média: [1 3 4]


In [27]:
anos_sem_acidente = np.sum(acidentes == 0, axis=1)
clientes_sem_acidente = np.where(anos_sem_acidente >= 2)[0]
print("Clientes com pelo menos 2 anos sem acidentes:", clientes_sem_acidente)


Clientes com pelo menos 2 anos sem acidentes: [1 3]


In [28]:
anos_sem_acidente = np.sum(acidentes == 0, axis=1)
clientes_sem_acidente = np.where(anos_sem_acidente >= 2)[0]
print("Clientes com pelo menos 2 anos sem acidentes:\n", clientes_sem_acidente)


Clientes com pelo menos 2 anos sem acidentes:
 [1 3]


In [22]:
def funcao(x, y):
    return 3*x + 2*y + x*y

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
resultado = funcao(x, y)
print("Resultado da função aplicada:\n", resultado)


Resultado da função aplicada:
 [15 26 39]


In [23]:
notas_provas = np.array([[1, 2, 1] * 3, [1, 2, 1] * 3, [1, 2, 1] * 3])
print("Notas adicionadas:\n", notas_provas)


Notas adicionadas:
 [[1 2 1 1 2 1 1 2 1]
 [1 2 1 1 2 1 1 2 1]
 [1 2 1 1 2 1 1 2 1]]
